# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync_files', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadSkipDays',
        ),
        migrations.RemoveField(
            model_name='uploadtransactionfile',
            name='consume',
        ),
        migrations.RemoveField(
            model_name='uploadtransactionfile',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='uploadtransactionfile',
            name='is_played',
        ),
        migrations.RemoveField(
            model_name='uploadtransactionfile',
            name='not_consumed',
        ),
    ]
