# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sync_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadskipdays',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadskipdays',
            name='skip_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadtransactionfile',
            name='hostname_created',
            field=models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadtransactionfile',
            name='transaction_file',
            field=models.FileField(upload_to='/Users/erikvw/source/bcpp/media'),
        ),
    ]
