language: python
python:
- 3.6
services:
- mysql
sudo: required
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- python3 -m flake8 django_collect_offline_files
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=django_collect_offline_files manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: iP+MaF7S0l7lq3Dq1B86K0PMqRNLWw3rhUWZuR63fHf/NtNDWzApB5qMDZBdjqj+YWct0w0qPR6vG6FNuZYnGUXQ3D330/Cfmf+7EQQ1i+S+zkG1TxaxKlwWpfWoNPhzb5I/GZtdgCt29H0BYW5hqswiFUWW0McKke51kNo5O9x3mlrJ2v86vw+/Q4OCVOwr4sKftSkQ5Mw/JwndRrbIoBDxuI1ae3thIbGmL+v/yNxZbAFs2lpQwMFZj8RI6DrEQW43dumqBiJkpCvA67UsMBHR9lW9v6/Vq7icyw1OtRkdBv1NUR5LLW3vuHUHPKUFUOIDrSXkeSqUmNZDfOJAo+z6U+p/W2bB9usAkoqLJvS5pixZqelypRQi+8C37uYwZW+l1ce7ttL5hqzJVIUoh6ghtv+q+n8c6nn+k9GG2G9wdWYWUOoblhwN5vqMD8/0KqeS0qd+SLd8Ev0U1GFipezt1J5Z59GOdKCyivuwCN8OG6xGkJKJVQbi0IMR5xtUuuecRH+lF49A3VI+G/DRKs9Y1koIbXB5jklJ1dXKYFcwv3uTzgQry905nF4rbBcDG12mCAYRFaYbeGe90qsga51hwgX3hdPoIznZW7qk7cySzWc/gyVpdcqAtv0OUWCPMTgpYsWdCcnDCwy7D7Cab9TpeVmEhMc9C4oJ0NkcMFo=
