language: python
python:
- 3.6
services:
- mysql
sudo: required
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 django_offline_files
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=django_offline_files manage.py test
after_success:
- coveralls
