language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 django_collect_offline_files
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=django_collect_offline_files manage.py test
after_success:
- coveralls
