# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 12:33
from __future__ import unicode_literals

import _socket
from django.db import migrations, models
import django_revision.revision_field
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.utils


class Migration(migrations.Migration):

    dependencies = [
        ('django_offline_files', '0002_auto_20170425_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedTransactionFileHistory',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('hostname', models.CharField(default=_socket.gethostname, max_length=100)),
                ('device_id', models.CharField(max_length=5, null=True)),
                ('batch_id', models.CharField(max_length=100)),
                ('prev_batch_id', models.CharField(max_length=100)),
                ('remote_path', models.CharField(max_length=200, null=True)),
                ('archive_path', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=50)),
                ('filesize', models.FloatField(null=True)),
                ('filetimestamp', models.DateTimeField(null=True)),
                ('exported', models.BooleanField(default=False)),
                ('exported_datetime', models.DateTimeField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_datetime', models.DateTimeField(null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmation_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Sent History',
                'verbose_name_plural': 'Sent History',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ImportedTransactionFileHistory',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default='mac2-2.local', help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('transaction_file', models.FileField(upload_to='')),
                ('filename', models.CharField(editable=False, max_length=50, null=True, unique=True)),
                ('batch_id', models.CharField(max_length=100, null=True)),
                ('prev_batch_id', models.CharField(max_length=100, null=True)),
                ('filedate', models.DateField(editable=False, null=True)),
                ('total', models.IntegerField(default=0, editable=False)),
                ('consumed', models.IntegerField(default=0, editable=False)),
                ('producer', models.TextField(editable=False, help_text='List of producers detected from the file.', max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='UploadTransactionFile',
        ),
        migrations.AddIndex(
            model_name='exportedtransactionfilehistory',
            index=models.Index(fields=['created'], name='edc_sync_fi_created_d9d422_idx'),
        ),
        migrations.AddIndex(
            model_name='exportedtransactionfilehistory',
            index=models.Index(fields=['sent_datetime'], name='edc_sync_fi_sent_da_b3fe1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exportedtransactionfilehistory',
            unique_together=set([('filename', 'hostname')]),
        ),
    ]
